import { useContext, useState } from 'react';
import Head from 'next/head';
import NavBar from './navbar';

const Header = () => {
  return (
    <>
      <Head>
        <title>Michael Ahearn - My Music</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <NavBar />
      </div>
    </>
  );
};

export default Header;
