import Head from 'next/head';
import NavBar from './navbar';
import styles from '../styles/Home.module.css';

const Header = () => {
  return (
    <>
      <Head>
        <title>Michael Ahearn - My Music</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar className={styles.navbar} />
    </>
  );
};

export default Header;
