import { useState } from 'react';
import Head from 'next/head';
import Stripe from 'stripe';
import styles from '../styles/Home.module.css';
import LibraryMusicIcon from '@mui/icons-material/LibraryMusic';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardMedia from '@mui/material/CardMedia';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Modal from '@mui/material/Modal';

export default function Home(props) {
  const products = props.products;
  const [showModal, setShowModal] = useState();
  const handleOpen = () => setShowModal(true);
  const handleClose = () => setShowModal(false);

  const modalStyle = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Michael Ahearn - My Music</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Michael Ahearn</h1>
        <h2>
          My Music <LibraryMusicIcon />
        </h2>
        <p className={styles.description}>
          Browse and purchase original sheet music here.
        </p>

        <div className={styles.grid}>
          {products?.map((product) => (
            <Card
              sx={{ display: 'flex', justifyContent: 'space-between' }}
              key={product.id}
              style={{ marginBottom: '1rem', width: '100%' }}
            >
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-around',
                  alignItems: 'flex-start',
                }}
              >
                <CardContent>
                  <Typography gutterBottom variant='h5' component='div'>
                    {product.name}
                  </Typography>
                  <Typography variant='body2' color='text.secondary'>
                    {product.description}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Button size='large' onClick={handleOpen}>
                    View Sample
                  </Button>
                  <Button size='large'>Add to Cart</Button>
                </CardActions>
              </Box>
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                }}
              >
                {product.images.length > 0 && (
                  <CardMedia
                    component='img'
                    sx={{ width: 300 }}
                    image={product.images[0]}
                    alt={product.name}
                  />
                )}
              </Box>
            </Card>
          ))}
        </div>
        <Modal
          open={showModal}
          onClose={handleClose}
          contentLabel='Sample score'
        >
          <button onClick={handleClose}>Close Modal</button>
          <Box sx={modalStyle}>
            Larger image of score goes here - just got to figure out how to do
            it.
          </Box>
        </Modal>
      </main>

      <footer className={styles.footer}>
        &copy; Michael Ahearn, Sydney 2022
      </footer>
    </div>
  );
}

export const getServerSideProps = async () => {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY ?? '', {
    apiVersion: '2020-08-27 ',
  });
  const response = await stripe.products.list();
  const products = response.data;
  return {
    props: {
      products,
    },
  };
};
