import React, { useState } from 'react';
import Head from 'next/head';
import Stripe from 'stripe';
import styles from '../styles/Home.module.css';
import LibraryMusicIcon from '@mui/icons-material/LibraryMusic';
import Box from '@mui/material/Box';
import Image from 'next/image';
import ShoppingCartCheckoutOutlinedIcon from '@mui/icons-material/ShoppingCartCheckoutOutlined';
import Modal from '@mui/material/Modal';

import { ProductCard } from '../components';

export default function Home(props) {
  const data = props.products;
  const [showModal, setShowModal] = useState(false);
  const [currentImage, setCurrentImage] = useState();
  const cartItemCount = 0; //Todo: set to the value of the user's cart length

  const handleClose = () => setShowModal(false);

  const handleOpen = (image) => {
    setShowModal(true);
    setCurrentImage(image);
  };

  const modalStyle = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '40vw',
    bgcolor: 'background.paper',
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
  };

  const cartIconStyle = {
    position: 'absolute',
    top: '46px',
    right: '40px',
    fontSize: '3em',
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Michael Ahearn - My Music</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <span className={styles.cartQuantityIndicator}>{cartItemCount}</span>
        <ShoppingCartCheckoutOutlinedIcon style={cartIconStyle} />
        <h1 className={styles.title}>Michael Ahearn</h1>
        <h2>
          My Music <LibraryMusicIcon />
        </h2>
        <p className={styles.description}>
          Browse and purchase original sheet music here.
        </p>

        <div className={styles.grid}>
          {data?.map((item) => (
            <ProductCard data={item} handleOpen={handleOpen} key={item.id} />
          ))}
        </div>
      </main>

      <div>
        <Modal
          open={showModal}
          onClose={handleClose}
          contentLabel='Sample score'
        >
          <Box sx={modalStyle}>
            <Image
              src={currentImage}
              alt='sample score'
              style={{ height: '100%', maxWidth: '90vw' }}
            />
          </Box>
        </Modal>
      </div>

      <footer className={styles.footer}>
        &copy; Michael Ahearn, Sydney 2022
      </footer>
    </div>
  );
}

export const getServerSideProps = async () => {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY ?? '', {
    apiVersion: '2020-08-27',
  });

  const productsWithPrices = await stripe.prices.list({
    expand: ['data.product'], // 🎉 Give me the product data too
  });
  const products = productsWithPrices.data;

  return {
    props: {
      products,
    },
  };
};
